name: Update README with Version Changes

on:
  push:
    tags:
      - "v*.*.*"  # `vX.Y.Z` のタグが付いたブランチをトリガー

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v4

      - name: 最新のコミット情報を取得
        id: get_commit
        run: |
          LATEST_COMMIT=$(git log -1 --pretty=format:"%s%n%n%b")
          echo "$LATEST_COMMIT" > commit_message.txt
          echo "COMMIT_MESSAGE<<EOF" >> $GITHUB_ENV
          cat commit_message.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
  
      - name: README.md にバージョン情報を追加
        run: |
          SUMMARY="${{ env.OPTIMIZED_SUMMARY }}"
          if [ -z "$SUMMARY" ] || [ "$SUMMARY" = "null" ] || [ "$SUMMARY" = "ERROR: No content received" ]; then
            SUMMARY="No summary generated"
          fi

          echo -e "\n## ${{ github.ref_name }}\n\n$SUMMARY" >> README.md
          cat README.md

      - name: 既存タグを削除して再作成プッシュ
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git tag -d ${{ github.ref_name }} || true
          git push --delete https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git ${{ github.ref_name }} || true

          git tag -a ${{ github.ref_name }} -m "Updated version tag"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git ${{ github.ref_name }}
